### ISSUE TITLE
I broke the award recommendation form

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#9]
Here is the data before I clicked "submit": 
![screenshot from 2018-10-17 15-28-20](https://user-images.githubusercontent.com/360015/47093533-51078080-d221-11e8-9b3d-04684f832e37.png)

Here is the error message I received:

**Comment by uckelman** [comment]
This was because the mail server wasn't turned on. Try now.

**Comment by SaraUckelman** [comment]
Can't even try now; can't get further than the "search" page.  Here's the error message I got searching for "Simon":

You broke it!
This is why we can't have nice things!

The exception was:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/op/dw_op/viewer.py", line 417, in recommend
    data['matches'] = resul
NameError: name 'resul' is not defined

**Comment by SaraUckelman** [comment]
I've now managed to get all the way through to the "recommendation sent!" page without any errors.

However, the page before that, which has the "submit" button on it, needs to have it's header text changed from "You have submitted" to "You wish to submit".

I'd change this myself, but I have no idea where in the repository this text is.

**Comment by uckelman** [comment]
Changed title text in 0f317a9b3.

**Comment by SaraUckelman** [comment]
The form now works for me.  Yda suggests in the "about me" part of the form, either list "persona" first and then "first" / "last" , OR say "modern first name" / "modern last name" b/c otherwise it wasn't clear what was being asked for.
